/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author raco1
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        adminPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        squarePanel = new javax.swing.JPanel();
        nintendoPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        cantDlcN = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spinnerIntegradorN = new javax.swing.JSpinner();
        spinnerNarrativoN = new javax.swing.JSpinner();
        spinnerNivelesN = new javax.swing.JSpinner();
        spinnerSpritesN = new javax.swing.JSpinner();
        spinnerLogicaN = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        spinnerDlcN = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        maxGuionesN = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cantSpritesN = new javax.swing.JLabel();
        cantSistemasN = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cantGuionesN = new javax.swing.JLabel();
        cantNivelesN = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        maxNivelesN = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        maxSpritesN = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        maxSistemasN = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        maxDlcN = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Ventana de administrador ");
        adminPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 220, 30));

        jLabel34.setText("Cargar parametros de simulacion ");
        adminPanel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, -1));

        jButton1.setText("jButton1");
        adminPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        jTabbedPane1.addTab("Admin", adminPanel);

        javax.swing.GroupLayout squarePanelLayout = new javax.swing.GroupLayout(squarePanel);
        squarePanel.setLayout(squarePanelLayout);
        squarePanelLayout.setHorizontalGroup(
            squarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        squarePanelLayout.setVerticalGroup(
            squarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Square Enix", squarePanel);

        nintendoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        nintendoPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, 770, 10));

        cantDlcN.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        cantDlcN.setForeground(new java.awt.Color(255, 0, 51));
        cantDlcN.setText("0");
        nintendoPanel.add(cantDlcN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 40, 30));

        jLabel5.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel5.setText("Disenadores de niveles");
        nintendoPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 200, 30));

        jLabel6.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel6.setText("artistas de sprites");
        nintendoPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 200, 30));

        jLabel7.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel7.setText("Programadores de logica");
        nintendoPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 200, 30));

        jLabel8.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel8.setText("Integrador");
        nintendoPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 200, 30));
        nintendoPanel.add(spinnerIntegradorN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 60, -1));
        nintendoPanel.add(spinnerNarrativoN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 60, -1));
        nintendoPanel.add(spinnerNivelesN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 60, -1));
        nintendoPanel.add(spinnerSpritesN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 60, -1));
        nintendoPanel.add(spinnerLogicaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 60, -1));

        jLabel9.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel9.setText("Desarroladores de DLC");
        nintendoPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 200, 30));
        nintendoPanel.add(spinnerDlcN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 60, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Pretendo", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Avance de juego");
        jLabel2.setAlignmentX(5.0F);
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nintendoPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 160, 30));

        jLabel10.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel10.setText("Desarrolador narrativo");
        nintendoPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Pretendo", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Juegos entregados");
        jLabel12.setAlignmentX(5.0F);
        jLabel12.setAlignmentY(0.0F);
        jLabel12.setFocusable(false);
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nintendoPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 160, 30));

        jLabel13.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel13.setText("Drive dlc");
        nintendoPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 200, 30));

        jLabel15.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel15.setText("juegos con DLc");
        nintendoPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 120, 30));

        jLabel16.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel16.setText("Drive Niveles ");
        nintendoPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 200, 30));

        jLabel17.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel17.setText("Drive Sprites");
        nintendoPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 200, 30));

        jLabel18.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel18.setText("Drive sistemas ");
        nintendoPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 200, 30));

        maxGuionesN.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        maxGuionesN.setText("25");
        nintendoPanel.add(maxGuionesN, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 30, 30));

        jLabel11.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("0");
        nintendoPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 40, 30));

        jLabel23.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 51));
        jLabel23.setText("0");
        nintendoPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 40, 30));

        cantSpritesN.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        cantSpritesN.setForeground(new java.awt.Color(255, 0, 51));
        cantSpritesN.setText("0");
        nintendoPanel.add(cantSpritesN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 40, 30));

        cantSistemasN.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        cantSistemasN.setForeground(new java.awt.Color(255, 0, 51));
        cantSistemasN.setText("0");
        nintendoPanel.add(cantSistemasN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 40, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Pretendo", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Proje ct  Manager");
        jLabel3.setAlignmentX(5.0F);
        jLabel3.setAlignmentY(0.0F);
        jLabel3.setFocusable(false);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nintendoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, 30));
        nintendoPanel.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 130, 20));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Pretendo", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("Elementos de Videojuego");
        jLabel26.setAlignmentX(5.0F);
        jLabel26.setAlignmentY(0.0F);
        jLabel26.setFocusable(false);
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nintendoPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 230, 30));

        jLabel27.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel27.setText("Drive guiones ");
        nintendoPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 200, 30));

        cantGuionesN.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        cantGuionesN.setForeground(new java.awt.Color(255, 0, 51));
        cantGuionesN.setText("0");
        nintendoPanel.add(cantGuionesN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 40, 30));

        cantNivelesN.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        cantNivelesN.setForeground(new java.awt.Color(255, 0, 51));
        cantNivelesN.setText("0");
        nintendoPanel.add(cantNivelesN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 40, 30));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Pretendo", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("        Desarrolladores");
        jLabel31.setAlignmentX(5.0F);
        jLabel31.setAlignmentY(0.0F);
        jLabel31.setFocusable(false);
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nintendoPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 160, 30));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Pretendo", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setText("Director");
        jLabel32.setAlignmentX(5.0F);
        jLabel32.setAlignmentY(0.0F);
        jLabel32.setFocusable(false);
        jLabel32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nintendoPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 80, 30));

        jLabel33.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel33.setText("Ganancias en bruto");
        nintendoPanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 160, 30));

        jLabel35.setFont(new java.awt.Font("Super Mario 256", 0, 10)); // NOI18N
        jLabel35.setText("Estado");
        nintendoPanel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 70, 30));

        jLabel36.setFont(new java.awt.Font("Super Mario 256", 0, 10)); // NOI18N
        jLabel36.setText("Estado");
        nintendoPanel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 70, 30));

        jLabel37.setFont(new java.awt.Font("Super Mario 256", 0, 10)); // NOI18N
        jLabel37.setText("Dinero descontado");
        nintendoPanel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 130, 30));

        jLabel38.setFont(new java.awt.Font("Super Mario 256", 0, 10)); // NOI18N
        jLabel38.setText("Faltas");
        nintendoPanel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 70, 30));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Pretendo", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("Para  entregar");
        jLabel28.setAlignmentX(5.0F);
        jLabel28.setAlignmentY(0.0F);
        jLabel28.setFocusable(false);
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nintendoPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 130, 30));

        jLabel39.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel39.setText("Juegos");
        nintendoPanel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 70, 30));

        jLabel40.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel40.setText("Costos operativos");
        nintendoPanel.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 160, 30));

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Pretendo", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 0, 0));
        jLabel41.setText("Utiliadad del estudio");
        jLabel41.setAlignmentX(5.0F);
        jLabel41.setAlignmentY(0.0F);
        jLabel41.setFocusable(false);
        jLabel41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nintendoPanel.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 30));

        jLabel42.setBackground(new java.awt.Color(255, 255, 255));
        jLabel42.setFont(new java.awt.Font("Pretendo", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 0, 0));
        jLabel42.setText("Economia");
        jLabel42.setAlignmentX(5.0F);
        jLabel42.setAlignmentY(0.0F);
        jLabel42.setFocusable(false);
        jLabel42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nintendoPanel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 90, 30));

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Pretendo", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 0, 0));
        jLabel43.setText("Deadline");
        jLabel43.setAlignmentX(5.0F);
        jLabel43.setAlignmentY(0.0F);
        jLabel43.setFocusable(false);
        jLabel43.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nintendoPanel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 90, 30));

        jLabel24.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel24.setText("de ");
        nintendoPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 30, 30));

        maxNivelesN.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        maxNivelesN.setText("20");
        nintendoPanel.add(maxNivelesN, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 30, 30));

        jLabel29.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel29.setText("de ");
        nintendoPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 30, 30));

        maxSpritesN.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        maxSpritesN.setText("55");
        nintendoPanel.add(maxSpritesN, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 30, 30));

        jLabel44.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel44.setText("de ");
        nintendoPanel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 30, 30));

        maxSistemasN.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        maxSistemasN.setText("35");
        nintendoPanel.add(maxSistemasN, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 30, 30));

        jLabel46.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel46.setText("de ");
        nintendoPanel.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 30, 30));

        maxDlcN.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        maxDlcN.setText("10");
        nintendoPanel.add(maxDlcN, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 30, 30));

        jLabel48.setFont(new java.awt.Font("Super Mario 256", 0, 13)); // NOI18N
        jLabel48.setText("de ");
        nintendoPanel.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 30, 30));

        jTabbedPane1.addTab("Nintendo", nintendoPanel);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminPanel;
    private javax.swing.JLabel cantDlcN;
    private javax.swing.JLabel cantGuionesN;
    private javax.swing.JLabel cantNivelesN;
    private javax.swing.JLabel cantSistemasN;
    private javax.swing.JLabel cantSpritesN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel maxDlcN;
    private javax.swing.JLabel maxGuionesN;
    private javax.swing.JLabel maxNivelesN;
    private javax.swing.JLabel maxSistemasN;
    private javax.swing.JLabel maxSpritesN;
    private javax.swing.JPanel nintendoPanel;
    private javax.swing.JSpinner spinnerDlcN;
    private javax.swing.JSpinner spinnerIntegradorN;
    private javax.swing.JSpinner spinnerLogicaN;
    private javax.swing.JSpinner spinnerNarrativoN;
    private javax.swing.JSpinner spinnerNivelesN;
    private javax.swing.JSpinner spinnerSpritesN;
    private javax.swing.JPanel squarePanel;
    // End of variables declaration//GEN-END:variables
}
